using System.Collections.Generic;
using System.Linq;

namespace CSharp007.CSC
{
    public class Countries
    {
        /// <summary>
        /// Get a list of all counties.
        /// </summary>
        public static readonly List<NameValue<string>> GetAllCountries = new List<NameValue<string>>
            {
                new NameValue {Name = "Afghanistan", Value = "1"},
                new NameValue {Name = "Albania", Value = "2"},
                new NameValue {Name = "Algeria", Value = "3"},
                new NameValue {Name = "American Samoa", Value = "4"},
                new NameValue {Name = "Andorra", Value = "5"},
                new NameValue {Name = "Angola", Value = "6"},
                new NameValue {Name = "Anguilla", Value = "7"},
                new NameValue {Name = "Antarctica", Value = "8"},
                new NameValue {Name = "Antigua And Barbuda", Value = "9"},
                new NameValue {Name = "Argentina", Value = "10"},
                new NameValue {Name = "Armenia", Value = "11"},
                new NameValue {Name = "Aruba", Value = "12"},
                new NameValue {Name = "Australia", Value = "13"},
                new NameValue {Name = "Austria", Value = "14"},
                new NameValue {Name = "Azerbaijan", Value = "15"},
                new NameValue {Name = "Bahamas The", Value = "16"},
                new NameValue {Name = "Bahrain", Value = "17"},
                new NameValue {Name = "Bangladesh", Value = "18"},
                new NameValue {Name = "Barbados", Value = "19"},
                new NameValue {Name = "Belarus", Value = "20"},
                new NameValue {Name = "Belgium", Value = "21"},
                new NameValue {Name = "Belize", Value = "22"},
                new NameValue {Name = "Benin", Value = "23"},
                new NameValue {Name = "Bermuda", Value = "24"},
                new NameValue {Name = "Bhutan", Value = "25"},
                new NameValue {Name = "Bolivia", Value = "26"},
                new NameValue {Name = "Bosnia and Herzegovina", Value = "27"},
                new NameValue {Name = "Botswana", Value = "28"},
                new NameValue {Name = "Bouvet Island", Value = "29"},
                new NameValue {Name = "Brazil", Value = "30"},
                new NameValue {Name = "British Indian Ocean Territory", Value = "31"},
                new NameValue {Name = "Brunei", Value = "32"},
                new NameValue {Name = "Bulgaria", Value = "33"},
                new NameValue {Name = "Burkina Faso", Value = "34"},
                new NameValue {Name = "Burundi", Value = "35"},
                new NameValue {Name = "Cambodia", Value = "36"},
                new NameValue {Name = "Cameroon", Value = "37"},
                new NameValue {Name = "Canada", Value = "38"},
                new NameValue {Name = "Cape Verde", Value = "39"},
                new NameValue {Name = "Cayman Islands", Value = "40"},
                new NameValue {Name = "Central African Republic", Value = "41"},
                new NameValue {Name = "Chad", Value = "42"},
                new NameValue {Name = "Chile", Value = "43"},
                new NameValue {Name = "China", Value = "44"},
                new NameValue {Name = "Christmas Island", Value = "45"},
                new NameValue {Name = "Cocos (Keeling) Islands", Value = "46"},
                new NameValue {Name = "Colombia", Value = "47"},
                new NameValue {Name = "Comoros", Value = "48"},
                new NameValue {Name = "Republic Of The Congo", Value = "49"},
                new NameValue {Name = "Democratic Republic Of The Congo", Value = "50"},
                new NameValue {Name = "Cook Islands", Value = "51"},
                new NameValue {Name = "Costa Rica", Value = "52"},
                new NameValue {Name = "Cote D'Ivoire (Ivory Coast)", Value = "53"},
                new NameValue {Name = "Croatia (Hrvatska)", Value = "54"},
                new NameValue {Name = "Cuba", Value = "55"},
                new NameValue {Name = "Cyprus", Value = "56"},
                new NameValue {Name = "Czech Republic", Value = "57"},
                new NameValue {Name = "Denmark", Value = "58"},
                new NameValue {Name = "Djibouti", Value = "59"},
                new NameValue {Name = "Dominica", Value = "60"},
                new NameValue {Name = "Dominican Republic", Value = "61"},
                new NameValue {Name = "East Timor", Value = "62"},
                new NameValue {Name = "Ecuador", Value = "63"},
                new NameValue {Name = "Egypt", Value = "64"},
                new NameValue {Name = "El Salvador", Value = "65"},
                new NameValue {Name = "Equatorial Guinea", Value = "66"},
                new NameValue {Name = "Eritrea", Value = "67"},
                new NameValue {Name = "Estonia", Value = "68"},
                new NameValue {Name = "Ethiopia", Value = "69"},
                new NameValue {Name = "External Territories of Australia", Value = "70"},
                new NameValue {Name = "Falkland Islands", Value = "71"},
                new NameValue {Name = "Faroe Islands", Value = "72"},
                new NameValue {Name = "Fiji Islands", Value = "73"},
                new NameValue {Name = "Finland", Value = "74"},
                new NameValue {Name = "France", Value = "75"},
                new NameValue {Name = "French Guiana", Value = "76"},
                new NameValue {Name = "French Polynesia", Value = "77"},
                new NameValue {Name = "French Southern Territories", Value = "78"},
                new NameValue {Name = "Gabon", Value = "79"},
                new NameValue {Name = "Gambia The", Value = "80"},
                new NameValue {Name = "Georgia", Value = "81"},
                new NameValue {Name = "Germany", Value = "82"},
                new NameValue {Name = "Ghana", Value = "83"},
                new NameValue {Name = "Gibraltar", Value = "84"},
                new NameValue {Name = "Greece", Value = "85"},
                new NameValue {Name = "Greenland", Value = "86"},
                new NameValue {Name = "Grenada", Value = "87"},
                new NameValue {Name = "Guadeloupe", Value = "88"},
                new NameValue {Name = "Guam", Value = "89"},
                new NameValue {Name = "Guatemala", Value = "90"},
                new NameValue {Name = "Guernsey and Alderney", Value = "91"},
                new NameValue {Name = "Guinea", Value = "92"},
                new NameValue {Name = "Guinea-Bissau", Value = "93"},
                new NameValue {Name = "Guyana", Value = "94"},
                new NameValue {Name = "Haiti", Value = "95"},
                new NameValue {Name = "Heard and McDonald Islands", Value = "96"},
                new NameValue {Name = "Honduras", Value = "97"},
                new NameValue {Name = "Hong Kong S.A.R.", Value = "98"},
                new NameValue {Name = "Hungary", Value = "99"},
                new NameValue {Name = "Iceland", Value = "100"},
                new NameValue {Name = "India", Value = "101"},
                new NameValue {Name = "Indonesia", Value = "102"},
                new NameValue {Name = "Iran", Value = "103"},
                new NameValue {Name = "Iraq", Value = "104"},
                new NameValue {Name = "Ireland", Value = "105"},
                new NameValue {Name = "Israel", Value = "106"},
                new NameValue {Name = "Italy", Value = "107"},
                new NameValue {Name = "Jamaica", Value = "108"},
                new NameValue {Name = "Japan", Value = "109"},
                new NameValue {Name = "Jersey", Value = "110"},
                new NameValue {Name = "Jordan", Value = "111"},
                new NameValue {Name = "Kazakhstan", Value = "112"},
                new NameValue {Name = "Kenya", Value = "113"},
                new NameValue {Name = "Kiribati", Value = "114"},
                new NameValue {Name = "Korea North", Value = "115"},
                new NameValue {Name = "Korea South", Value = "116"},
                new NameValue {Name = "Kuwait", Value = "117"},
                new NameValue {Name = "Kyrgyzstan", Value = "118"},
                new NameValue {Name = "Laos", Value = "119"},
                new NameValue {Name = "Latvia", Value = "120"},
                new NameValue {Name = "Lebanon", Value = "121"},
                new NameValue {Name = "Lesotho", Value = "122"},
                new NameValue {Name = "Liberia", Value = "123"},
                new NameValue {Name = "Libya", Value = "124"},
                new NameValue {Name = "Liechtenstein", Value = "125"},
                new NameValue {Name = "Lithuania", Value = "126"},
                new NameValue {Name = "Luxembourg", Value = "127"},
                new NameValue {Name = "Macau S.A.R.", Value = "128"},
                new NameValue {Name = "Macedonia", Value = "129"},
                new NameValue {Name = "Madagascar", Value = "130"},
                new NameValue {Name = "Malawi", Value = "131"},
                new NameValue {Name = "Malaysia", Value = "132"},
                new NameValue {Name = "Maldives", Value = "133"},
                new NameValue {Name = "Mali", Value = "134"},
                new NameValue {Name = "Malta", Value = "135"},
                new NameValue {Name = "Man (Isle of)", Value = "136"},
                new NameValue {Name = "Marshall Islands", Value = "137"},
                new NameValue {Name = "Martinique", Value = "138"},
                new NameValue {Name = "Mauritania", Value = "139"},
                new NameValue {Name = "Mauritius", Value = "140"},
                new NameValue {Name = "Mayotte", Value = "141"},
                new NameValue {Name = "Mexico", Value = "142"},
                new NameValue {Name = "Micronesia", Value = "143"},
                new NameValue {Name = "Moldova", Value = "144"},
                new NameValue {Name = "Monaco", Value = "145"},
                new NameValue {Name = "Mongolia", Value = "146"},
                new NameValue {Name = "Montserrat", Value = "147"},
                new NameValue {Name = "Morocco", Value = "148"},
                new NameValue {Name = "Mozambique", Value = "149"},
                new NameValue {Name = "Myanmar", Value = "150"},
                new NameValue {Name = "Namibia", Value = "151"},
                new NameValue {Name = "Nauru", Value = "152"},
                new NameValue {Name = "Nepal", Value = "153"},
                new NameValue {Name = "Netherlands Antilles", Value = "154"},
                new NameValue {Name = "Netherlands The", Value = "155"},
                new NameValue {Name = "New Caledonia", Value = "156"},
                new NameValue {Name = "New Zealand", Value = "157"},
                new NameValue {Name = "Nicaragua", Value = "158"},
                new NameValue {Name = "Niger", Value = "159"},
                new NameValue {Name = "Nigeria", Value = "160"},
                new NameValue {Name = "Niue", Value = "161"},
                new NameValue {Name = "Norfolk Island", Value = "162"},
                new NameValue {Name = "Northern Mariana Islands", Value = "163"},
                new NameValue {Name = "Norway", Value = "164"},
                new NameValue {Name = "Oman", Value = "165"},
                new NameValue {Name = "Pakistan", Value = "166"},
                new NameValue {Name = "Palau", Value = "167"},
                new NameValue {Name = "Palestinian Territory Occupied", Value = "168"},
                new NameValue {Name = "Panama", Value = "169"},
                new NameValue {Name = "Papua new Guinea", Value = "170"},
                new NameValue {Name = "Paraguay", Value = "171"},
                new NameValue {Name = "Peru", Value = "172"},
                new NameValue {Name = "Philippines", Value = "173"},
                new NameValue {Name = "Pitcairn Island", Value = "174"},
                new NameValue {Name = "Poland", Value = "175"},
                new NameValue {Name = "Portugal", Value = "176"},
                new NameValue {Name = "Puerto Rico", Value = "177"},
                new NameValue {Name = "Qatar", Value = "178"},
                new NameValue {Name = "Reunion", Value = "179"},
                new NameValue {Name = "Romania", Value = "180"},
                new NameValue {Name = "Russia", Value = "181"},
                new NameValue {Name = "Rwanda", Value = "182"},
                new NameValue {Name = "Saint Helena", Value = "183"},
                new NameValue {Name = "Saint Kitts And Nevis", Value = "184"},
                new NameValue {Name = "Saint Lucia", Value = "185"},
                new NameValue {Name = "Saint Pierre and Miquelon", Value = "186"},
                new NameValue {Name = "Saint Vincent And The Grenadines", Value = "187"},
                new NameValue {Name = "Samoa", Value = "188"},
                new NameValue {Name = "San Marino", Value = "189"},
                new NameValue {Name = "Sao Tome and Principe", Value = "190"},
                new NameValue {Name = "Saudi Arabia", Value = "191"},
                new NameValue {Name = "Senegal", Value = "192"},
                new NameValue {Name = "Serbia", Value = "193"},
                new NameValue {Name = "Seychelles", Value = "194"},
                new NameValue {Name = "Sierra Leone", Value = "195"},
                new NameValue {Name = "Singapore", Value = "196"},
                new NameValue {Name = "Slovakia", Value = "197"},
                new NameValue {Name = "Slovenia", Value = "198"},
                new NameValue {Name = "Smaller Territories of the UK", Value = "199"},
                new NameValue {Name = "Solomon Islands", Value = "200"},
                new NameValue {Name = "Somalia", Value = "201"},
                new NameValue {Name = "South Africa", Value = "202"},
                new NameValue {Name = "South Georgia", Value = "203"},
                new NameValue {Name = "South Sudan", Value = "204"},
                new NameValue {Name = "Spain", Value = "205"},
                new NameValue {Name = "Sri Lanka", Value = "206"},
                new NameValue {Name = "Sudan", Value = "207"},
                new NameValue {Name = "Suriname", Value = "208"},
                new NameValue {Name = "Svalbard And Jan Mayen Islands", Value = "209"},
                new NameValue {Name = "Swaziland", Value = "210"},
                new NameValue {Name = "Sweden", Value = "211"},
                new NameValue {Name = "Switzerland", Value = "212"},
                new NameValue {Name = "Syria", Value = "213"},
                new NameValue {Name = "Taiwan", Value = "214"},
                new NameValue {Name = "Tajikistan", Value = "215"},
                new NameValue {Name = "Tanzania", Value = "216"},
                new NameValue {Name = "Thailand", Value = "217"},
                new NameValue {Name = "Togo", Value = "218"},
                new NameValue {Name = "Tokelau", Value = "219"},
                new NameValue {Name = "Tonga", Value = "220"},
                new NameValue {Name = "Trinidad And Tobago", Value = "221"},
                new NameValue {Name = "Tunisia", Value = "222"},
                new NameValue {Name = "Turkey", Value = "223"},
                new NameValue {Name = "Turkmenistan", Value = "224"},
                new NameValue {Name = "Turks And Caicos Islands", Value = "225"},
                new NameValue {Name = "Tuvalu", Value = "226"},
                new NameValue {Name = "Uganda", Value = "227"},
                new NameValue {Name = "Ukraine", Value = "228"},
                new NameValue {Name = "United Arab Emirates", Value = "229"},
                new NameValue {Name = "United Kingdom", Value = "230"},
                new NameValue {Name = "United States", Value = "231"},
                new NameValue {Name = "United States Minor Outlying Islands", Value = "232"},
                new NameValue {Name = "Uruguay", Value = "233"},
                new NameValue {Name = "Uzbekistan", Value = "234"},
                new NameValue {Name = "Vanuatu", Value = "235"},
                new NameValue {Name = "Vatican City State (Holy See)", Value = "236"},
                new NameValue {Name = "Venezuela", Value = "237"},
                new NameValue {Name = "Vietnam", Value = "238"},
                new NameValue {Name = "Virgin Islands (British)", Value = "239"},
                new NameValue {Name = "Virgin Islands (US)", Value = "240"},
                new NameValue {Name = "Wallis And Futuna Islands", Value = "241"},
                new NameValue {Name = "Western Sahara", Value = "242"},
                new NameValue {Name = "Yemen", Value = "243"},
                new NameValue {Name = "Yugoslavia", Value = "244"},
                new NameValue {Name = "Zambia", Value = "245"},
                new NameValue {Name = "Zimbabwe", Value = "246"}
            };

        /// <summary>
        /// Get countries based on the search result
        /// </summary>
        /// <param name="name">fitler countires by name contaning values</param>
        /// <returns>List of filtered countires</returns>
        public static List<NameValue<string>> GetCountriesByNameContaining(string name)
        {
            return GetAllCountries.Where(c => c.Name.ToLower().Contains(name.ToLower())).ToList();

        }

        /// <summary>
        /// Get country based on Id
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns>Get a country based on Id</returns>
        public static NameValue<string> GetCountryByValue(string id)
        {
            return GetAllCountries.Where(c => c.Value == id).FirstOrDefault();

        }

        public static List<NameValue<string>> GetCountriesByName(string name)
        {
            return GetAllCountries.Where(c => c.Name.ToLower() == name.ToLower()).ToList();
        }
    }
}

